version: '3'

services:
  app:
    build:
      context: ../spring-image/
      dockerfile: Dockerfile
    container_name: spring
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:latest'
    container_name: db
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"